from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_user, name='login_user'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_user, name='logout_user'),
    path('home/', views.home, name='home'),
    path('remove-recipe/<int:recipe_id>/', views.remove_recipe, name='remove-recipe'),
    path('remove-inventory/<int:inventory_id>/', views.remove_inventory, name='remove-inventory'),
    path('set-default-inventory/<int:inventory_id>/', views.set_default_inventory, name='set-default-inventory'),
    path('check-missing-ingredients-recipe', views.check_missing_ingredients_from_recipe,
         name='check-missing-ingredients-recipe'),
    path('add-recipe/', views.add_recipe, name='add-recipe'),
    path('add-recipe/<int:recipe_id>/', views.add_recipe, name='add-recipe'),
    path('add-ingredient-recipe/<int:recipe_id>/', views.add_ingredient_to_recipe,
         name='add-ingredient-recipe'),
    path('add-ingredient-recipe/<int:recipe_id>/<int:ingredient_id>/', views.add_ingredient_to_recipe,
         name='add-ingredient-recipe'),
    path('load-ingredient/', views.load_ingredients_from_inventory, name='load-ingredient'),
    path('add-selected-ingredients/', views.add_selected_ingredients, name='add-selected-ingredients'),
    path('add-step-recipe/<int:recipe_id>/<int:step_id>/', views.add_step_to_recipe,
         name='add-step-recipe'),
    path('add-step-recipe/<int:recipe_id>/', views.add_step_to_recipe,
         name='add-step-recipe'),
    path('view-recipe/<int:recipe_id>/', views.view_recipes, name='view-recipe'),
    path('remove-ingredient-recipe/<int:ingredient_id>/', views.remove_ingredient_form_recipe,
         name='remove-ingredient-recipe'),
    path('remove-step-recipe/<int:step_id>/', views.remove_step_from_recipe, name='remove-step-recipe'),
    path('add-inventory/', views.add_inventory, name='add-inventory'),
    path('add-inventory/<int:inventory_id>/', views.add_inventory, name='add-inventory'),
    path('list-ingredient/<int:inventory_id>/', views.list_ingredient, name='list_ingredient'),
    path('manage-ingredient-inventory/<int:inventory_id>/<int:ingredient_id>/', views.manage_ingredients_inventory,
         name='manage-ingredient-inventory'),
    path('manage-ingredient-inventory/<int:inventory_id>/', views.manage_ingredients_inventory,
         name='manage-ingredient-inventory'),
    path('remove-ingredient-inventory/<int:ingredient_id>/', views.remove_ingredient_from_inventory,
         name='remove-ingredient-inventory'),
]
