# Generated by Django 5.0.2 on 2024-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
