# Generated by Django 5.0.2 on 2024-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0002_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
