# Generated by Django 5.0.2 on 2024-02-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0003_remove_users_birth_date_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
