# Generated by Django 5.0.2 on 2024-02-29 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('beerRecipe', '0004_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.JSONField()),
                ('id_category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.category')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_unit', models.CharField(max_length=100)),
                ('id_ingredient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_unit', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('id_ingredient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.ingredient')),
                ('id_inventory',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(through='beerRecipe.InventoryIngredient', to='beerRecipe.ingredient'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ibu', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'id_user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients',
                 models.ManyToManyField(through='beerRecipe.IngredientRecipe', to='beerRecipe.ingredient')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.recipe'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.recipe')),
            ],
        ),
    ]
