# Generated by Django 5.0.2 on 2024-02-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('beerRecipe', '0005_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE beerRecipe_recipe_ingredients RENAME TO beerRecipe_IngredientRecipe',
                    reverse_sql='ALTER TABLE beerRecipe_IngredientRecipe RENAME TO beerRecipe_recipe_ingredients',
                ),

                migrations.RunSQL(
                    sql='ALTER TABLE beerRecipe_inventory_ingredients RENAME TO beerRecipe_InventoryIngredient',
                    reverse_sql='ALTER TABLE beerRecipe_InventoryIngredient RENAME TO beerRecipe_inventory_ingredients',
                ),
            ],

            state_operations=[
                migrations.CreateModel(
                    name='IngredientRecipe',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('id_recipe',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.Recipe')),
                        ('id_ingredient',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='beerRecipe.Ingredient')),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('measurement_unit', models.CharField(max_length=100)),
                    ],
                ),

                migrations.CreateModel(
                    name='InventoryIngredient',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('id_ingredient',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.Ingredient')),
                        ('id_inventory',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.Inventory')),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('measurement_unit', models.CharField(max_length=100)),
                        ('expiry_date', models.DateField()),
                    ],
                ),

                migrations.AlterField(
                    model_name='recipe',
                    name='ingredients',
                    field=models.ManyToManyField(to='beerRecipe.Recipe', through='beerRecipe.IngredientRecipe'),
                ),

                migrations.AlterField(
                    model_name='inventory',
                    name='ingredients',
                    field=models.ManyToManyField(to='beerRecipe.Inventory', through='beerRecipe.InventoryIngredient'),
                ),
            ],
        ),

        migrations.AddField(
            model_name='IngredientRecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),

        migrations.AddField(
            model_name='IngredientRecipe',
            name='measurement_unit',
            field=models.CharField(max_length=100),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='measurement_unit',
            field=models.CharField(max_length=100),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
