# Generated by Django 5.0.2 on 2024-02-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beerRecipe', '0006_through_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ingredients',
            field=models.ManyToManyField(through='beerRecipe.InventoryIngredient', to='beerRecipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='beerRecipe.IngredientRecipe', to='beerRecipe.ingredient'),
        ),
        migrations.AddField(
            model_name='IngredientRecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),

        migrations.AddField(
            model_name='IngredientRecipe',
            name='measurement_unit',
            field=models.CharField(max_length=100),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='measurement_unit',
            field=models.CharField(max_length=100),
        ),

        migrations.AddField(
            model_name='InventoryIngredient',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
