# Generated by Django 5.0.2 on 2024-02-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0007_alter_inventory_ingredients_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
