# Generated by Django 5.0.2 on 2024-02-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0008_alter_inventoryingredient_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='measurement_unit',
            field=models.CharField(max_length=50),
        ),
    ]
