# Generated by Django 5.0.2 on 2024-03-02 15:41

import django_yaml_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0009_alter_ingredientrecipe_measurement_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-creation_date'], 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name_plural': 'Steps'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='property',
            field=django_yaml_field.fields.YAMLField(),
        ),
    ]
