# Generated by Django 5.0.2 on 2024-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0010_alter_category_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['index'], 'verbose_name_plural': 'Steps'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Default value', max_length=200),
            preserve_default=False,
        ),
    ]
