# Generated by Django 5.0.2 on 2024-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0012_ingredient_comment_inventory_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
