# Generated by Django 5.0.2 on 2024-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0013_alter_inventoryingredient_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='original_unit',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
