# Generated by Django 5.0.2 on 2024-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0015_ingredient_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('ingredients', models.ManyToManyField(to='beerRecipe.ingredient')),
            ],
        ),
    ]
