# Generated by Django 5.0.2 on 2024-05-31 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerRecipe', '0015_ingredient_producer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('basic_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_ingredient', to='beerRecipe.ingredient')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquivalentClass_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equivalent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.equivalentclass')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerRecipe.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='equivalentclass',
            name='ingredients',
            field=models.ManyToManyField(through='beerRecipe.EquivalentClass_Ingredients', to='beerRecipe.ingredient'),
        ),
    ]
